import 'package:flutter/material.dart';

abstract final class AppColors {
  static const Color surface = Color(0xFF131313);
  static const Color surfaceDim = Color(0xFF131313);
  static const Color surfaceBright = Color(0xFF3A3939);
  static const Color surfaceContainerLowest = Color(0xFF0E0E0E);
  static const Color surfaceContainerLow = Color(0xFF1C1B1B);
  static const Color surfaceContainer = Color(0xFF201F1F);
  static const Color surfaceContainerHigh = Color(0xFF2A2A2A);
  static const Color surfaceContainerHighest = Color(0xFF353534);
  static const Color onSurface = Color(0xFFE5E2E1);
  static const Color onSurfaceVariant = Color(0xFFD0C5AF);
  static const Color inverseSurface = Color(0xFFE5E2E1);
  static const Color inverseOnSurface = Color(0xFF313030);
  static const Color outline = Color(0xFF99907C);
  static const Color outlineVariant = Color(0xFF4D4635);
  static const Color surfaceTint = Color(0xFFEAC249);
  static const Color primary = Color(0xFFEAC249);
  static const Color onPrimary = Color(0xFF3D2F00);
  static const Color primaryContainer = Color(0xFFC5A028);
  static const Color onPrimaryContainer = Color(0xFF493800);
  static const Color inversePrimary = Color(0xFF745B00);
  static const Color secondary = Color(0xFFC8C6C5);
  static const Color onSecondary = Color(0xFF303030);
  static const Color secondaryContainer = Color(0xFF474746);
  static const Color onSecondaryContainer = Color(0xFFB7B5B4);
  static const Color tertiary = Color(0xFFC8C6C6);
  static const Color onTertiary = Color(0xFF303030);
  static const Color tertiaryContainer = Color(0xFFA5A4A4);
  static const Color onTertiaryContainer = Color(0xFF3A3A3A);
  static const Color error = Color(0xFFFFB4AB);
  static const Color onError = Color(0xFF690005);
  static const Color errorContainer = Color(0xFF93000A);
  static const Color onErrorContainer = Color(0xFFFFDAD6);
  static const Color background = Color(0xFF131313);
  static const Color onBackground = Color(0xFFE5E2E1);
  static const Color surfaceVariant = Color(0xFF353534);

  static const Color floor = Color(0xFF0A0A0A);
  static const Color card = Color(0xFF141414);
  static const Color overlay = Color(0xFF1F1F1F);
  static const Color border = Color(0xFF2D2D2D);
  static const Color goldBorder = Color(0xFF332E22);
  static const Color mutedText = Color(0xFF94A3B8);
  static const Color white = Color(0xFFFFFFFF);
  static const Color transparent = Colors.transparent;
  static const Color success = Color(0xFF7DDCA5);
  static const Color onSuccess = Color(0xFF062D18);
  static const Color successContainer = Color(0xFF123D25);
  static const Color warning = Color(0xFFE0B35B);
}
